#!/bin/bash

mysql <<EOF
DROP DATABASE IF EXISTS example;
CREATE DATABASE example;
USE example;
DROP TABLE IF EXISTS users;
CREATE TABLE users (id SERIAL, name VARCHAR(255));
exit
EOF

mysqldump example > dump_example.sql
mysql <<EOF
DROP DATABASE IF EXISTS sample;
CREATE DATABASE sample;
exit
EOF

mysql sample < dump_example.sql

mysql <<EOF
USE example;
SHOW TABLES;
DESCRIBE users;
USE sample;
SHOW TABLES;
DESCRIBE users;
exit
EOF

mysqldump mysql help_keyword --where='help_keyword_id<100' > dump100.sql

